[package]
name = "tls_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustls = "0.20"
rustls-pemfile = "1.0"
mio = { version = "0.8.*", features = ["net", "os-poll"] }

[features]
